GET http://localhost:3000


### Post asset
POST http://localhost:3000/assets
Content-Type: application/json

{
  "id": "asset2",
  "symbol": "A2",
  "price": 84
}

### get Asset
GET http://localhost:3000/assets
Content-Type: application/json

### get wallet
GET http://localhost:3000/wallets
Content-Type: application/json

### Post wallet
POST http://localhost:3000/wallets
Content-Type: application/json

{
  "id": "wallet1"
}

### get wallet param
GET http://localhost:3000/wallets/wallet1/assets
Content-Type: application/json

### Post wallet params
POST http://localhost:3000/wallets/wallet1/assets
Content-Type: application/json

{
  "asset_id": "asset2",
  "shares": 5
}


### Post order
POST http://localhost:3000/orders
Content-Type: application/json

{
  "asset_id": "asset2",
  "shares": 5,
  "wallet_id": "wallet1",
  "price": 70,
  "type": "BUY"
}