GET http://localhost:3000


### Post asset
POST http://localhost:3000/assets
Content-Type: application/json

{
  "id": "asset1",
  "symbol": "A1",
  "price": 14
}

### get Asset
GET http://localhost:3000/assets
Content-Type: application/json

### get wallet
GET http://localhost:3000/wallets
Content-Type: application/json

### Post wallet
POST http://localhost:3000/wallets
Content-Type: application/json

{
  "id": "wallet1"
}